#pragma once

// This file was generated by the monomial_basis_1d.py Python script
// Do not edit it by hand

namespace hhg {

class MonomialBasis1D {
public:
  static real_t eval(uint_t basis, real_t x) {
    switch(basis) {
      case 0:
        return 1;
      case 1:
        return x;
      case 2:
        return pow(x, 2);
      case 3:
        return pow(x, 3);
      case 4:
        return pow(x, 4);
      case 5:
        return pow(x, 5);
      case 6:
        return pow(x, 6);
      case 7:
        return pow(x, 7);
      default:
        WALBERLA_ABORT("Polynomial basis " << basis << " was not generated");
    }
  }
};

}