#pragma once

// This file was generated by the monomial_basis_2d.py Python script
// Do not edit it by hand

namespace hhg {

class MonomialBasis2D {
public:
  static real_t eval(uint_t, uint_t basis, const Point2D &x) {
    switch(basis) {
      case 0:
        return 1;
      case 1:
        return x[0];
      case 2:
        return x[1];
      case 3:
        return x[0]*x[0];
      case 4:
        return x[0]*x[1];
      case 5:
        return x[1]*x[1];
      case 6:
        return x[0]*x[0]*x[0];
      case 7:
        return x[1]*(x[0]*x[0]);
      case 8:
        return x[0]*(x[1]*x[1]);
      case 9:
        return x[1]*x[1]*x[1];
      case 10:
        return x[0]*x[0]*x[0]*x[0];
      case 11:
        return x[1]*(x[0]*x[0]*x[0]);
      case 12:
        return (x[0]*x[0])*(x[1]*x[1]);
      case 13:
        return x[0]*(x[1]*x[1]*x[1]);
      case 14:
        return x[1]*x[1]*x[1]*x[1];
      case 15:
        return x[0]*x[0]*x[0]*x[0]*x[0];
      case 16:
        return x[1]*(x[0]*x[0]*x[0]*x[0]);
      case 17:
        return (x[1]*x[1])*(x[0]*x[0]*x[0]);
      case 18:
        return (x[0]*x[0])*(x[1]*x[1]*x[1]);
      case 19:
        return x[0]*(x[1]*x[1]*x[1]*x[1]);
      case 20:
        return x[1]*x[1]*x[1]*x[1]*x[1];
      case 21:
        return x[0]*x[0]*x[0]*x[0]*x[0]*x[0];
      case 22:
        return x[1]*(x[0]*x[0]*x[0]*x[0]*x[0]);
      case 23:
        return (x[1]*x[1])*(x[0]*x[0]*x[0]*x[0]);
      case 24:
        return (x[0]*x[0]*x[0])*(x[1]*x[1]*x[1]);
      case 25:
        return (x[0]*x[0])*(x[1]*x[1]*x[1]*x[1]);
      case 26:
        return x[0]*(x[1]*x[1]*x[1]*x[1]*x[1]);
      case 27:
        return x[1]*x[1]*x[1]*x[1]*x[1]*x[1];
      case 28:
        return x[0]*x[0]*x[0]*x[0]*x[0]*x[0]*x[0];
      case 29:
        return x[1]*(x[0]*x[0]*x[0]*x[0]*x[0]*x[0]);
      case 30:
        return (x[1]*x[1])*(x[0]*x[0]*x[0]*x[0]*x[0]);
      case 31:
        return (x[1]*x[1]*x[1])*(x[0]*x[0]*x[0]*x[0]);
      case 32:
        return (x[0]*x[0]*x[0])*(x[1]*x[1]*x[1]*x[1]);
      case 33:
        return (x[0]*x[0])*(x[1]*x[1]*x[1]*x[1]*x[1]);
      case 34:
        return x[0]*(x[1]*x[1]*x[1]*x[1]*x[1]*x[1]);
      case 35:
        return x[1]*x[1]*x[1]*x[1]*x[1]*x[1]*x[1];
      default:
      WALBERLA_ABORT("Polynomial basis " << basis << " was not generated");
    }
  }
};

}