#!/bin/bash
#PBS -N timingTest11level6
#PBS -l select=2:node_type=rome:mpiprocs=120:node_type_mem=256gb
#PBS -l walltime=00:20:00
#PBS -o /zhome/academic/HLRS/xgu/xgutnv/hyteg/hyteg/apps/2024-convbench/test_prm_runners_dir/level_6/pbsoutdir

echo $PBS_O_WORKDIR

cd $PBS_O_WORKDIR

module load hlrs-software-stack/previous

module load gcc/12.2.0
module load openmpi/4.1.5

mpirun -np 240 /zhome/academic/HLRS/xgu/xgutnv/hyteg/hyteg-build/apps/2024-convbench/SphericalShellBenchRotationMinimalMinimal /zhome/academic/HLRS/xgu/xgutnv/hyteg/hyteg/apps/2024-convbench/test_prm_runners_dir/level_6/prmdir/SphericalShellBenchRotationMinimalMinimal_11_level6.prm
