/*
 * Copyright (c) 2017-2019 Daniel Drzisga, Dominik Thoennes.
 *
 * This file is part of HyTeG
 * (see https://i10git.cs.fau.de/hyteg/hyteg).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */
#pragma once

// This file was generated by the monomial_basis_1d.py Python script
// Do not edit it by hand

namespace hyteg {

class MonomialBasis1D {
public:
  static real_t eval(uint_t basis, real_t x) {
    switch(basis) {
      case 0:
        return 1;
      case 1:
        return x;
      case 2:
        return x*x;
      case 3:
        return x*x*x;
      case 4:
        return x*x*x*x;
      case 5:
        return x*x*x*x*x;
      case 6:
        return x*x*x*x*x*x;
      case 7:
        return x*x*x*x*x*x*x;
      case 8:
        return x*x*x*x*x*x*x*x;
      case 9:
        return x*x*x*x*x*x*x*x*x;
      case 10:
        return x*x*x*x*x*x*x*x*x*x;
      case 11:
        return x*x*x*x*x*x*x*x*x*x*x;
      case 12:
        return x*x*x*x*x*x*x*x*x*x*x*x;
      default:
        WALBERLA_ABORT("Polynomial basis " << basis << " was not generated");
    }
  }
};

}