/*
 * Copyright (c) 2019 Nils Kohl, Dominik Thoennes.
 *
 * This file is part of HyTeG
 * (see https://i10git.cs.fau.de/hyteg/hyteg).
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

//////////////////////////////////////////////////////////////////////////////
// This file is generated! To fix issues, please fix them in the generator. //
//////////////////////////////////////////////////////////////////////////////

#include "prolongate_3D_macrocell_P2_push_from_edgedofs_level_0_to_1.hpp"

namespace hyteg {
namespace P2 {
namespace macrocell {
namespace generated {

static void prolongate_3D_macrocell_P2_push_from_edgedofs_level_0_to_1_level_any(real_t const * RESTRICT const _data_edgeCoarseSrc_X, real_t const * RESTRICT const _data_edgeCoarseSrc_XY, real_t const * RESTRICT const _data_edgeCoarseSrc_XZ, real_t const * RESTRICT const _data_edgeCoarseSrc_Y, real_t const * RESTRICT const _data_edgeCoarseSrc_YZ, real_t const * RESTRICT const _data_edgeCoarseSrc_Z, real_t * RESTRICT _data_edgeFineDst_X, real_t * RESTRICT _data_edgeFineDst_XY, real_t * RESTRICT _data_edgeFineDst_XYZ, real_t * RESTRICT _data_edgeFineDst_XZ, real_t * RESTRICT _data_edgeFineDst_Y, real_t * RESTRICT _data_edgeFineDst_YZ, real_t * RESTRICT _data_edgeFineDst_Z, real_t * RESTRICT _data_vertexFineDst, int coarse_level, double num_neighbor_cells_edge0, double num_neighbor_cells_edge1, double num_neighbor_cells_edge2, double num_neighbor_cells_edge3, double num_neighbor_cells_edge4, double num_neighbor_cells_edge5, double num_neighbor_cells_face0, double num_neighbor_cells_face1, double num_neighbor_cells_face2, double num_neighbor_cells_face3)
{
   {
      for (int ctr_3 = 0; ctr_3 < 1; ctr_3 += 1)
      {
         for (int ctr_2 = 0; ctr_2 < 1; ctr_2 += 1)
         {
            // vertex 0
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge0;
               _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.75*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge0;
               _data_edgeFineDst_X[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.5*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.5*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))] = 0.25*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))] + _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))];
               _data_vertexFineDst[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*((1 << (coarse_level + 1)) + 3)) / (6)) - (((-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 3)) / (6)) + 1] = 1.0*_data_edgeCoarseSrc_X[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge0;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge1;
               _data_edgeFineDst_Y[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Y[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge1;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.25*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_X[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_Z[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Z[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))] = 0.25*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))] + _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))];
               _data_vertexFineDst[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*((1 << (coarse_level + 1)) + 3)) / (6)) - (((-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 3)) / (6))] = 1.0*_data_edgeCoarseSrc_Y[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge1;
               _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge3;
               _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge3;
               _data_edgeFineDst_Z[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Z[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.25*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))] = 0.25*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))] + _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))];
               _data_vertexFineDst[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*((1 << (coarse_level + 1)) + 3)) / (6))] = 1.0*_data_edgeCoarseSrc_Z[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge3;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.75*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge2;
               _data_edgeFineDst_XY[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge2;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.5*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.5*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_X[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face0;
               _data_edgeFineDst_XZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))] = 0.25*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))] + _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))];
               _data_vertexFineDst[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*((1 << (coarse_level + 1)) + 3)) / (6)) - (((-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 3)) / (6)) + 1] = 1.0*_data_edgeCoarseSrc_XY[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge2;
               _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.75*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge4;
               _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge4;
               _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_XZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_Z[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.5*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.5*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))] = 0.25*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))] + _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))];
               _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_X[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face1;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_vertexFineDst[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*((1 << (coarse_level + 1)) + 3)) / (6)) + 1] = 1.0*_data_edgeCoarseSrc_XZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge4;
               _data_edgeFineDst_YZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_YZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge5;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.75*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge5;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.25*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] = _data_edgeFineDst_YZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6)) + 1] + 0.25*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_Z[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Z[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_XZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XZ[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_Y[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face2;
               _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] = _data_edgeFineDst_XY[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*(1 << (coarse_level + 1))) / (6))] + 0.5*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_face3;
               _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))] = 0.25*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))] + _data_edgeFineDst_XYZ[2*ctr_1 + 2*ctr_2*(-2*ctr_3 + (1 << (coarse_level + 1))) - ((2*ctr_2*(2*ctr_2 + 1)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) - 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)) / (6)) + ((((1 << (coarse_level + 1)) - 1)*((1 << (coarse_level + 1)) + 1)*(1 << (coarse_level + 1))) / (6))];
               _data_vertexFineDst[2*ctr_1 + (2*ctr_2 + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1) - (((2*ctr_2 + 1)*(2*ctr_2 + 2)) / (2)) - (((-2*ctr_3 + (1 << (coarse_level + 1)))*(-2*ctr_3 + (1 << (coarse_level + 1)) + 1)*(-2*ctr_3 + (1 << (coarse_level + 1)) + 2)) / (6)) + ((((1 << (coarse_level + 1)) + 1)*((1 << (coarse_level + 1)) + 2)*((1 << (coarse_level + 1)) + 3)) / (6))] = 1.0*_data_edgeCoarseSrc_YZ[ctr_1 + ctr_2*(-ctr_3 + (1 << (coarse_level)) + 1) - ((ctr_2*(ctr_2 + 1)) / (2)) - (((-ctr_3 + (1 << (coarse_level)))*(-ctr_3 + (1 << (coarse_level)) + 1)*(-ctr_3 + (1 << (coarse_level)) + 2)) / (6)) + ((((1 << (coarse_level)) + 1)*((1 << (coarse_level)) + 2)*(1 << (coarse_level))) / (6))]/num_neighbor_cells_edge5;
            }
            // edge 0
            for (int ctr_1 = 1; ctr_1 < (1 << (coarse_level)) - 1; ctr_1 += 1)
            {
               
            }
            // vertex 1
            for (int ctr_1 = (1 << (coarse_level)) - 1; ctr_1 < (1 << (coarse_level)); ctr_1 += 1)
            {
               
            }
         }
         for (int ctr_2 = 1; ctr_2 < -ctr_3 + (1 << (coarse_level)) - 1; ctr_2 += 1)
         {
            // edge 1
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               
            }
            // face 0
            for (int ctr_1 = 1; ctr_1 < -ctr_2 + (1 << (coarse_level)) - 1; ctr_1 += 1)
            {
               
            }
            // edge 2
            for (int ctr_1 = -ctr_2 + (1 << (coarse_level)) - 1; ctr_1 < -ctr_2 + (1 << (coarse_level)); ctr_1 += 1)
            {
               
            }
         }
         for (int ctr_2 = -ctr_3 + (1 << (coarse_level)) - 1; ctr_2 < -ctr_3 + (1 << (coarse_level)); ctr_2 += 1)
         {
            // vertex 2
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               
            }
         }
      }
      for (int ctr_3 = 1; ctr_3 < (1 << (coarse_level)) - 1; ctr_3 += 1)
      {
         for (int ctr_2 = 0; ctr_2 < 1; ctr_2 += 1)
         {
            // edge 3
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               
            }
            // face 1
            for (int ctr_1 = 1; ctr_1 < -ctr_3 + (1 << (coarse_level)) - 1; ctr_1 += 1)
            {
               
            }
            // edge 4
            for (int ctr_1 = -ctr_3 + (1 << (coarse_level)) - 1; ctr_1 < -ctr_3 + (1 << (coarse_level)); ctr_1 += 1)
            {
               
            }
         }
         for (int ctr_2 = 1; ctr_2 < -ctr_3 + (1 << (coarse_level)) - 1; ctr_2 += 1)
         {
            // face 2
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               
            }
            // cell (inner)
            for (int ctr_1 = 1; ctr_1 < -ctr_2 - ctr_3 + (1 << (coarse_level)) - 1; ctr_1 += 1)
            {
               
            }
            // face 3
            for (int ctr_1 = -ctr_2 - ctr_3 + (1 << (coarse_level)) - 1; ctr_1 < -ctr_2 - ctr_3 + (1 << (coarse_level)); ctr_1 += 1)
            {
               
            }
         }
         for (int ctr_2 = -ctr_3 + (1 << (coarse_level)) - 1; ctr_2 < -ctr_3 + (1 << (coarse_level)); ctr_2 += 1)
         {
            // edge 5
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               
            }
         }
      }
      for (int ctr_3 = (1 << (coarse_level)) - 1; ctr_3 < (1 << (coarse_level)); ctr_3 += 1)
      {
         for (int ctr_2 = 0; ctr_2 < 1; ctr_2 += 1)
         {
            // vertex 3
            for (int ctr_1 = 0; ctr_1 < 1; ctr_1 += 1)
            {
               
            }
         }
      }
   }
}


void prolongate_3D_macrocell_P2_push_from_edgedofs_level_0_to_1(real_t const * RESTRICT const _data_edgeCoarseSrc_X, real_t const * RESTRICT const _data_edgeCoarseSrc_XY, real_t const * RESTRICT const _data_edgeCoarseSrc_XZ, real_t const * RESTRICT const _data_edgeCoarseSrc_Y, real_t const * RESTRICT const _data_edgeCoarseSrc_YZ, real_t const * RESTRICT const _data_edgeCoarseSrc_Z, real_t * RESTRICT _data_edgeFineDst_X, real_t * RESTRICT _data_edgeFineDst_XY, real_t * RESTRICT _data_edgeFineDst_XYZ, real_t * RESTRICT _data_edgeFineDst_XZ, real_t * RESTRICT _data_edgeFineDst_Y, real_t * RESTRICT _data_edgeFineDst_YZ, real_t * RESTRICT _data_edgeFineDst_Z, real_t * RESTRICT _data_vertexFineDst, int coarse_level, double num_neighbor_cells_edge0, double num_neighbor_cells_edge1, double num_neighbor_cells_edge2, double num_neighbor_cells_edge3, double num_neighbor_cells_edge4, double num_neighbor_cells_edge5, double num_neighbor_cells_face0, double num_neighbor_cells_face1, double num_neighbor_cells_face2, double num_neighbor_cells_face3)
{
    switch( coarse_level )
    {

    default:
        prolongate_3D_macrocell_P2_push_from_edgedofs_level_0_to_1_level_any(_data_edgeCoarseSrc_X, _data_edgeCoarseSrc_XY, _data_edgeCoarseSrc_XZ, _data_edgeCoarseSrc_Y, _data_edgeCoarseSrc_YZ, _data_edgeCoarseSrc_Z, _data_edgeFineDst_X, _data_edgeFineDst_XY, _data_edgeFineDst_XYZ, _data_edgeFineDst_XZ, _data_edgeFineDst_Y, _data_edgeFineDst_YZ, _data_edgeFineDst_Z, _data_vertexFineDst, coarse_level, num_neighbor_cells_edge0, num_neighbor_cells_edge1, num_neighbor_cells_edge2, num_neighbor_cells_edge3, num_neighbor_cells_edge4, num_neighbor_cells_edge5, num_neighbor_cells_face0, num_neighbor_cells_face1, num_neighbor_cells_face2, num_neighbor_cells_face3);
        break;
    }
}
    

} // namespace generated
} // namespace macrocell
} // namespace P2
} // namespace hyteg