#!/bin/bash
#PBS -l select=16:node_type=rome:mpiprocs=120:node_type_mem=256gb
#PBS -l walltime=23:59:59
#PBS -N sph_exp_ad_boundoff

source /zhome/academic/HLRS/xgu/xgutnv/loadModules.sh 

mpirun -np 1920 /zhome/academic/HLRS/xgu/xgutnv/hyteg-build-gcc/apps/2024-convbench/SphericalShellBenchRotationMinimal /zhome/academic/HLRS/xgu/xgutnv/hyteg/hyteg/apps/2024-convbench/SphericalShellBenchRotationMinimal.prm
