waLBerla_add_test_executable( P3FunctionTest P3FunctionTest.cpp )
target_link_libraries       ( P3FunctionTest hyteg walberla::core )
waLBerla_execute_test(NAME P3FunctionTest1 COMMAND $<TARGET_FILE:P3FunctionTest> PROCESSES 1)
waLBerla_execute_test(NAME P3FunctionTest2 COMMAND $<TARGET_FILE:P3FunctionTest> PROCESSES 2)

if (HYTEG_BUILD_WITH_PETSC AND WALBERLA_DOUBLE_ACCURACY)
  waLBerla_add_test_executable( P3PetscTest P3PetscTest.cpp )
  target_link_libraries       ( P3PetscTest hyteg )
  waLBerla_execute_test(NAME P3PetscTest1 COMMAND $<TARGET_FILE:P3PetscTest> PROCESSES 1)
  waLBerla_execute_test(NAME P3PetscTest2 COMMAND $<TARGET_FILE:P3PetscTest> PROCESSES 2)
  if (NOT WALBERLA_CXX_COMPILER_IS_INTELLLVM)
    waLBerla_execute_test(NAME P3PetscTest3 COMMAND $<TARGET_FILE:P3PetscTest> PROCESSES 8)
  endif ()
endif ()

waLBerla_add_test_executable( P3DiffusionTest P3DiffusionTest.cpp )
target_link_libraries       ( P3DiffusionTest hyteg walberla::core )
waLBerla_execute_test(NAME P3DiffusionTest1 COMMAND $<TARGET_FILE:P3DiffusionTest> PROCESSES 1)
waLBerla_execute_test(NAME P3DiffusionTest2 COMMAND $<TARGET_FILE:P3DiffusionTest> PROCESSES 2)
